#!/usr/bin/env bash
# a bash scripts that installs Nginx and configure it to listen on port 80
# then serve a page that prints "Hello World"

apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World\n" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
