#!/usr/bin/env bash
# a bash scripts that installs Nginx and configure it to listen on port 80
# then serve a page that prints "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
