#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*
echo "ENABLED=1" > /etc/default/haproxy
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 353188-web-01 54.172.56.188 check
   server 353188-web-02 100.25.118.208 check
" >> /etc/haproxy/haproxy.cfg
service haproxy start
