#!/usr/bin/env bash
#Short script to debug and start nginx without running status
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
rm /run/nginx.pid
