#!/usr/bin/env bash
# Bash script that displays "to infinity and beyond" indefinitely with sleep 2 between each iteration and "I am invicible!!!" when receiving a SIGTERM signal

while true; do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invicible!!!"' SIGTERM
done
