#!/usr/bin/env bash
# Bash script that displays 'Best School' 10 times, but displays 'Hi' after 9th iteration and then new line
i=0
while ((i < 10))
do
	echo 'Best School'
	((i++))
	if [ $i -eq 9 ]
	then
		echo 'Hi'
	fi
done
