#!/usr/bin/env bash
# Bash script that displays: the content of current directory, in a list and where only the part of the name after the first dash is diplayed
list=$(ls)
for i in $list
do
	echo "$i" | cut -d'-' -f 2
done
